# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eaa45e061935e2443df3bd28e8fdb26eb38e245db77c4f00dff8ba7bfc07787c3a5c8f703216a5048de157e1e334fee956a40c7f7fdf71dd1e830d0446480eec

test:
  secret_key_base: 19ca70c9b570444f5c8496ea6102038a5e1586537202f27cb6f1166c4dd5539042dcd94fa7749081989f454680bf4cd4826a77f1b4ea72dee438a47ff5d79964

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
